### ISSUE TITLE
Browser randomly fails to start in docker container

### ISSUE THREAD

**Issue by MMaster** [iv-org/youtube-trusted-session-generator#3]
When running the docker container the browser fails to start quite often throwing the following exception:

```[INFO] internally launching GUI (X11 environment)
[INFO] launching the python script
[INFO] launching browser.
Traceback (most recent call last):
  File "/usr/app/src/index.py", line 46, in <module>
    loop().run_until_complete(main())
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/app/src/index.py", line 10, in main
    browser = await start(headless=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/util.py", line 74, in start
    return await Browser.create(config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/browser.py", line 87, in create
    await instance.start()
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/browser.py", line 343, in start
    raise Exception(
Exception:
                ---------------------
                Failed to connect to browser
                ---------------------
                One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True

Exception ignored in atexit callback: <function deconstruct_browser at 0x7fbf3f225580>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/util.py", line 124, in deconstruct_browser
    _.stop()
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/browser.py", line 545, in stop
    asyncio.get_event_loop().create_task(self.connection.aclose())
                                         ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'aclose'
```

Catching the exception and trying again after 3 seconds until it succeeds seems to fix this issue.

**Comment by unixfox** [comment]
How much RAM does your system have?

Could you try to add `--shm-size=2G` in the `docker run` command?

**Comment by MMaster** [comment]
Currently the VM has 8GB RAM and half of it is free. I sure can increase the shared memory size for that, but I'm not really sure how that should help. I tried it and even the very first run failed.

The browser starts successfully 1 time and then fails to start 3 times on 4 different runs (it was doing the same thing with headless browser when X was not part of the docker image). 

I've fixed the issue by simply doing try except on the start call and doing max 5 retries before giving up and it works, so memory doesn't seem to be the issue here.

**Comment by unixfox** [comment]
Ok. That's strange because I can't replicate the issue. I launched the script 5 times in a row and never had the issue:

Are you sure you are running the latest version of the script?

![image](https://github.com/user-attachments/assets/01f91390-ec0f-46ca-a599-c0989b8cf892)

**Comment by unixfox** [comment]
Related: https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1949 and https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1896

**Comment by MMaster** [comment]
Yeah I am on latest version. 

The related issues that you marked are actually 2 separate issues. 
The first one happens even if the browser starts successfully and returns the tokens - I suspect it is because the async event loop is not properly stopped, but instead sys.exit is called.
The second one may be related, but the solutions there don't really apply since I don't have any zombie processes, the docker container stops after the run with no leftovers and also the corrupted user data doesn't apply since it's immutable docker image.

Anyway I noticed even on stackoverflow that some people have this issue randomly with nodriver with no reliable solution.

**Comment by unixfox** [comment]
Ok I was able to reproduce the issue on a VM with just 2 cores and 1GB of RAM.

**Comment by MMaster** [comment]
> Ok I was able to reproduce the issue on a VM with just 2 cores and 1GB of RAM.

fyi: Yesterday it stopped happening completely on the original VM. But it happened on dedicated machine with 128 GB RAM and 10 cores / 20 threads. It's completely random for me.

**Comment by unixfox** [comment]
Ok I have narrowed down the issue, nodriver doesn't wait enough time before giving up trying to connect chromium instance: https://github.com/ultrafunkamsterdam/nodriver/blob/main/nodriver/core/browser.py#L340-L346

I have pushed a dirty patch in the Dockerfile for waiting more time: https://github.com/iv-org/youtube-trusted-session-generator/commit/0551c92227287aaa32d3a559635dde8f7ea9b5a1#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R22. I validated that it works fine on my VM with 2vCPU and 1GB of RAM.

But I'm waiting for an official implementation, for which I have created a PR:
- https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1956
- https://github.com/unixfox/nodriver/pull/1

**Comment by markus583** [comment]
Hi, even with the dirty patch and also when increasing the sleep time further, I still get the same error.
VM resources are not the issue, it has much more than 2vCPU and 1GB of RAM.

Did anyone encounter this issues in other settings/has fixes for them? Thanks!

**Comment by amaumene** [comment]
I had the same problem, I fixed it with `browser = await start(headless=False, sandbox=False)`

**Comment by hashamyounis9** [comment]
Hey @markus583!
hope you are doing well.
any progress on this issue?

**Comment by markus583** [comment]
> Hey @markus583! hope you are doing well. any progress on this issue?

Hi @hashamyounis9 , thanks but no update from my side as I did not have the chance to try again since then.

**Comment by bitnol** [comment]
> Ok I have narrowed down the issue, nodriver doesn't wait enough time before giving up trying to connect chromium instance: https://github.com/ultrafunkamsterdam/nodriver/blob/main/nodriver/core/browser.py#L340-L346
> 
> I have pushed a dirty patch in the Dockerfile for waiting more time: [0551c92#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R22](https://github.com/iv-org/youtube-trusted-session-generator/commit/0551c92227287aaa32d3a559635dde8f7ea9b5a1#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R22). I validated that it works fine on my VM with 2vCPU and 1GB of RAM.
> 
> But I'm waiting for an official implementation, for which I have created a PR:
> 
> * [Would like to submit a PR to ultrafunkamsterdam/nodriver ultrafunkamsterdam/undetected-chromedriver#1956](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1956)
> * [allow to specify more retries when connecting to the browser instance unixfox/nodriver#1](https://github.com/unixfox/nodriver/pull/1)

I have tested the change of wait time but there was no change. 
But when I changed the headless=False to True in extractor.py L104, it started working.

**Comment by unixfox** [comment]
> > Ok I have narrowed down the issue, nodriver doesn't wait enough time before giving up trying to connect chromium instance: https://github.com/ultrafunkamsterdam/nodriver/blob/main/nodriver/core/browser.py#L340-L346
> > 
> > I have pushed a dirty patch in the Dockerfile for waiting more time: [0551c92#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R22](https://github.com/iv-org/youtube-trusted-session-generator/commit/0551c92227287aaa32d3a559635dde8f7ea9b5a1#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R22). I validated that it works fine on my VM with 2vCPU and 1GB of RAM.
> > 
> > But I'm waiting for an official implementation, for which I have created a PR:
> > 
> > * [Would like to submit a PR to ultrafunkamsterdam/nodriver ultrafunkamsterdam/undetected-chromedriver#1956](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1956)
> > * [allow to specify more retries when connecting to the browser instance unixfox/nodriver#1](https://github.com/unixfox/nodriver/pull/1)
> 
> I have tested the change of wait time but there was no change. 
> But when I changed the headless=False to True in extractor.py L104, it started working.

The token should be invalid if headless is true. Did it work for you?

**Comment by achiragaming** [comment]
same thing happend with my vps too 
```
[INFO] internally launching GUI (X11 environment)
[INFO] starting Xvfb
[INFO] launching chromium instance
2024/12/07 18:54:45.655 [extractor] [INFO] update started
Traceback (most recent call last):
  File "/app/potoken-generator.py", line 4, in <module>
    potoken_generator.main.main()
  File "/app/potoken_generator/main.py", line 98, in main
    loop.run_until_complete(main_task)
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/potoken_generator/main.py", line 35, in run
    token = await potoken_extractor.run_once()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/potoken_generator/extractor.py", line 46, in run_once
    await self._update()
  File "/app/potoken_generator/extractor.py", line 91, in _update
    await asyncio.wait_for(self._perform_update(), timeout=600)
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/app/potoken_generator/extractor.py", line 104, in _perform_update
    browser = await nodriver.start(headless=False,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/util.py", line 74, in start
    return await Browser.create(config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/browser.py", line 87, in create
    await instance.start()
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/browser.py", line 343, in start
    raise Exception(
Exception: 
                ---------------------
                Failed to connect to browser
                ---------------------
                One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True 
                
Exception ignored in atexit callback: <function deconstruct_browser at 0x7f9180998540>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/util.py", line 124, in deconstruct_browser

    _.stop()
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/browser.py", line 545, in stop
    asyncio.get_event_loop().create_task(self.connection.aclose())
                                         ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'aclose'```

**Comment by Svenito** [comment]
Just wanted to chip in here that I was having the same issue. I found this thread and the `--shm-size=2G` didn't resolve anything, but `--shm-size=3G` made it work reliably.

**Comment by CelluloidRacer2** [comment]
> `--shm-size=2G` didn't resolve anything, but `--shm-size=3G` made it work reliably.

Trying `--shm-size=3G` through `--shm-size=8G` didn't work for me. I'm guessing it has to do with load times & the above mentioned race condition.

Do you know what CPU do you have on that host? I'm running on baremetal with an older `Xeon E5-1650v1`.

**Comment by Svenito** [comment]
The box is running an `Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz` - it's in a homelab running linux

**Comment by CelluloidRacer2** [comment]
Definitely was not a CPU issue

My issue was absolutely not related to the code- I ended up discovering a network issue that caused some downloads to fail, which I'm assuming made Chromium's first launch fail, and consequently return the error seen here

Note to self: don't forget to set TCP-MSS/MTU on Wireguard's loopback adapters if passing outbound network traffic across a VPN on the network side (and not on network clients)

**Comment by JC9mm** [comment]
Docker on Truenas worked like a charm. I had no issues. 
![snip](https://github.com/user-attachments/assets/d64165c9-da15-4291-9110-85e09864992b)

**Comment by davralin** [comment]
> Note to self: don't forget to set TCP-MSS/MTU on Wireguard's loopback adapters if passing outbound network traffic across a VPN on the network side (and not on network clients)


Also note to self: This is probably also relevant on tailscale, so stop tailscale even though you are local.

**Comment by unixfox** [comment]
https://github.com/iv-org/youtube-trusted-session-generator/commit/14573b40aadaf8d03a112ddc8570ea9676a3a863

**Comment by DandyTush** [comment]
this finally worked for me after many attempts
```
sudo docker run --shm-size=8G quay.io/invidious/youtube-trusted-session-generator
```
